# Generated by Django 3.1.7 on 2022-07-26 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surat_menyurat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disposisi',
            name='batas_waktu',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='disposisi',
            name='surat',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='surat_menyurat.surat'),
        ),
        migrations.AlterField(
            model_name='disposisi',
            name='tujuan_disposisi',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='surat_menyurat.struktural'),
        ),
    ]
