# Generated by Django 3.1.7 on 2022-07-26 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surat_menyurat', '0002_auto_20220726_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disposisi',
            name='surat',
        ),
        migrations.AddField(
            model_name='disposisi',
            name='suratmasuk',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='surat_menyurat.suratmasuk'),
        ),
    ]
