# Generated by Django 3.1.7 on 2022-07-26 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surat_menyurat', '0003_auto_20220726_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disposisi',
            name='suratmasuk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='surat_menyurat.suratmasuk'),
        ),
        migrations.AlterField(
            model_name='disposisi',
            name='tujuan_disposisi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='surat_menyurat.struktural'),
        ),
    ]
