# Generated by Django 3.1.7 on 2022-08-13 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surat_menyurat', '0004_auto_20220726_1918'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disposisi',
            options={'verbose_name_plural': 'Disposisi Masuk'},
        ),
        migrations.AlterField(
            model_name='disposisi',
            name='suratmasuk',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='surat_menyurat.suratmasuk'),
        ),
        migrations.CreateModel(
            name='Disposisi_keluar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batas_waktu', models.CharField(max_length=255)),
                ('isi_disposisi', models.TextField(blank=True, null=True)),
                ('catatan', models.CharField(max_length=255)),
                ('sifat_disposisi', models.CharField(choices=[('Biasa', 'Biasa'), ('Segera', 'Segera'), ('Penting', 'Penting'), ('Rahasia', 'Rahasia')], default='', max_length=255)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('suratkeluar', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='surat_menyurat.suratkeluar')),
                ('tujuan_disposisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='surat_menyurat.struktural')),
            ],
            options={
                'verbose_name_plural': 'Disposisi Keluar',
            },
        ),
    ]
